{% set name = "django-mptt-tree-editor" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-mptt-tree-editor-{{ version }}.tar.gz
  sha256: 6f2db74b9fa3a592dd69f952138ad2470610a8e50ea2184a08f2a0c5a0911c0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=1.4
    - django-mptt >=0.4

test:
  imports:
    - mptt_tree_editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://bitbucket.org/san/django-mptt-tree-editor
  summary: Provides FeinCMS's mptt admin tree editor as a separate app
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
